### Normalisation des données fichier: INA_Normalized
(Pour chaque chaîne on regarde sur les sujets de chaque mois la proportion dans chacun des thèmes pour pouvoir comparer les chaînes entre-elles)

Il y a sans doute des moyens plus astucieux et moins laborieux de faire la normalisation mais voilà celle qui a été utilisé. 

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Decoder le fichier source

In [8]:
df=pd.read_csv('INA.csv', sep=';', encoding='latin-1') #le fichier original

#### Couper les 6 derniers mois pour comparer des anénes complètes

In [4]:
df2=df[:2183]

### Faire la somme des sujets pour chaque chaine pour chaque mois (les constantes de normalisation)

In [6]:
norm=[]
for column in df[['TF1', 'France 2', 'France 3', 'Canal +', 'Arte', 'M6']]:
    norm.append(df2.groupby(['MOIS'])[column].sum())

### Tout remettre dans l'ordre (lexicographique à mensuel) aout avril ... 

In [7]:
l=[4,3,8,1,7,6,5,0,11,10,9,2]
new_idx=[]
for i in range(12):
    new_idx.append(l[i]*12+l[i])

In [8]:
new_idx

[52, 39, 104, 13, 91, 78, 65, 0, 143, 130, 117, 26]

In [12]:
new_idx_full=np.arange(52,52+12+1)
k=12
for i in range(11):
    new_idx_full=np.concatenate((new_idx_full,np.arange(new_idx[i+1],new_idx[i+1]+k+1)))

In [18]:
new_idx_full

array([ 52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38])

#### Maintenant que l'on a le tableau des permutations complètent on peut remettre dans l'ordre.

In [15]:
norm_array=np.array(norm)

In [21]:
norm_array_reorder=norm_array[:,new_idx_full]

#### Il faut encore changer les dimensions en faisant attention à ne pas mélanger les dimensions pour diviser membre à membre les deux tableaux

In [24]:
norm_tensor=np.reshape(norm_array_reorder, (6,12,13)) #Chaque array une chaine et dans l'ordre chaque mois

In [25]:
norm_tensor=np.swapaxes(norm_tensor,1,2)

In [28]:
norm_final=np.repeat(norm_tensor.flatten(), 14)

In [29]:
norm_final=norm_final.reshape((6,len(norm_final)//6))

In [30]:
norm_final=norm_final.transpose()

In [31]:
norm_final

array([[705., 666., 390., 105., 254., 279.],
       [705., 666., 390., 105., 254., 279.],
       [705., 666., 390., 105., 254., 279.],
       ...,
       [450., 495., 369.,  89., 250., 375.],
       [450., 495., 369.,  89., 250., 375.],
       [450., 495., 369.,  89., 250., 375.]])

### Effectuer la normalisation

In [33]:
data=np.array(df2[['TF1', 'France 2', 'France 3', 'Canal +', 'Arte', 'M6']])

In [34]:
data

array([[214., 191.,  88.,  18.,  40.,  49.],
       [ 27.,  42.,  35.,   4.,   0.,  23.],
       [ 35.,  18.,  10.,   1.,   8.,  11.],
       ...,
       [ 17.,  17.,  20.,   0.,   3.,  16.],
       [  7.,   6.,   3.,   5.,  12.,  10.],
       [ 87.,  82.,  67.,  11.,  28.,  77.]])

In [35]:
data_normalized=np.divide(data, norm_final[:-1])

C:\Users\Flow\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [36]:
data_normalized

array([[0.3035461 , 0.28678679, 0.22564103, 0.17142857, 0.15748031,
        0.17562724],
       [0.03829787, 0.06306306, 0.08974359, 0.03809524, 0.        ,
        0.08243728],
       [0.04964539, 0.02702703, 0.02564103, 0.00952381, 0.03149606,
        0.03942652],
       ...,
       [0.03777778, 0.03434343, 0.05420054, 0.        , 0.012     ,
        0.04266667],
       [0.01555556, 0.01212121, 0.00813008, 0.05617978, 0.048     ,
        0.02666667],
       [0.19333333, 0.16565657, 0.18157182, 0.12359551, 0.112     ,
        0.20533333]])

#### Repackager dans un dataframe

In [37]:
df_norm=pd.DataFrame(data=data_normalized, columns=['TF1', 'France 2', 'France 3', 'Canal +', 'Arte', 'M6'])

In [38]:
df2_norm=df2

In [353]:
df2_norm['Totaux']=df['TF1']+df['France 2']+df['France 3']+df['Canal +']+ df['Arte']+ df['M6'] #chaque valeur est la proportion du thème par rapport aux nombres de sujets abordées ce mois-ci pour chaque chaine télévisée.

C:\Users\Flow\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


##### Pour verifier que tout va bien la somme des proportions par thème fait 1 et il y a 6 thèmes.

In [356]:
np.sum(np.array(df2_norm['Totaux'][:14]))#YEEEEEEEES

6.000000000000001

In [40]:
df2_norm

MOIS             THEMATIQUES       TF1  France 2  France 3  \
0     janv.-05            Catastrophes  0.303546  0.286787  0.225641   
1     janv.-05         Culture-loisirs  0.038298  0.063063  0.089744   
2     janv.-05                Economie  0.049645  0.027027  0.025641   
3     janv.-05               Education  0.019858  0.018018  0.010256   
4     janv.-05           Environnement  0.043972  0.037538  0.038462   
5     janv.-05            Faits divers  0.034043  0.028529  0.023077   
6     janv.-05       Histoire-hommages  0.051064  0.057057  0.061538   
7     janv.-05           International  0.073759  0.091592  0.138462   
8     janv.-05                 Justice  0.028369  0.040541  0.041026   
9     janv.-05        Politique France  0.038298  0.037538  0.064103   
10    janv.-05                   Santé  0.029787  0.028529  0.038462   
11    janv.-05  Sciences et techniques  0.039716  0.016517  0.028205   
12    janv.-05                 Société  0.197163  0.193694  0.166667   
13    janv.-05                   Sport  0.052482  0.073574  0.048718   
14    févr.-05            Catastrophes  0.059155  0.046225  0.034031   
15    févr.-05         Culture-loisirs  0.057746  0.101695  0.060209   
16    févr.-05                Economie  0.064789  0.066256  0.062827   
17    févr.-05               Education  0.038028  0.047766  0.057592   
18    févr.-05           Environnement  0.064789  0.038521  0.031414   
19    févr.-05            Faits divers  0.023944  0.024653  0.034031   
20    févr.-05       Histoire-hommages  0.019718  0.018490  0.031414   
21    févr.-05           International  0.140845  0.169492  0.212042   
22    févr.-05                 Justice  0.078873  0.080123  0.112565   
23    févr.-05        Politique France  0.032394  0.027735  0.034031   
24    févr.-05                   Santé  0.070423  0.063174  0.052356   
25    févr.-05  Sciences et techniques  0.023944  0.023112  0.026178   
26    févr.-05                 Société  0.249296  0.203390  0.175393   
27    févr.-05                   Sport  0.076056  0.089368  0.075916   
28     mars-05            Catastrophes  0.053592  0.050867  0.057692   
29     mars-05         Culture-loisirs  0.054732  0.093642  0.081197   
...        ...                     ...       ...       ...       ...   
2153   oct.-17  Sciences et techniques  0.033088  0.014730  0.011013   
2154   oct.-17                 Société  0.180147  0.181669  0.156388   
2155   oct.-17                   Sport  0.056985  0.024550  0.019824   
2156   nov.-17            Catastrophes  0.029412  0.034934  0.060000   
2157   nov.-17         Culture-loisirs  0.081448  0.034934  0.034286   
2158   nov.-17                Economie  0.128959  0.174672  0.134286   
2159   nov.-17               Education  0.036199  0.010917  0.028571   
2160   nov.-17           Environnement  0.061086  0.041485  0.040000   
2161   nov.-17            Faits divers  0.047511  0.043668  0.074286   
2162   nov.-17       Histoire-hommages  0.020362  0.021834  0.020000   
2163   nov.-17           International  0.117647  0.139738  0.082857   
2164   nov.-17                 Justice  0.042986  0.063319  0.060000   
2165   nov.-17        Politique France  0.090498  0.135371  0.117143   
2166   nov.-17                   Santé  0.049774  0.043668  0.057143   
2167   nov.-17  Sciences et techniques  0.031674  0.010917  0.025714   
2168   nov.-17                 Société  0.192308  0.196507  0.191429   
2169   nov.-17                   Sport  0.070136  0.048035  0.074286   
2170   déc.-17            Catastrophes  0.133333  0.107071  0.162602   
2171   déc.-17         Culture-loisirs  0.071111  0.032323  0.054201   
2172   déc.-17                Economie  0.140000  0.139394  0.081301   
2173   déc.-17               Education  0.026667  0.010101  0.010840   
2174   déc.-17           Environnement  0.037778  0.056566  0.021680   
2175   déc.-17            Faits divers  0.035556  0.024242  0.075881   
2176   déc.-17       Histoire-hommages  0.146667  

### Save to pkl format

In [5]:
#df2_norm.to_pickle("./INA_normalized.pkl")